spring:
  datasource:
    url: jdbc:mysql://learndocker-mysql:3306/docker?createDatabaseIfNotExist=true
    username: docker
    password: docker
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080